AllCops:
  DisplayCopNames: true
  TargetRubyVersion:
    2.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SignalException:
  EnforcedStyle: only_raise

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Metrics/AbcSize:
  Exclude:
    - lib/todo_lint/cli.rb

Metrics/MethodLength:
  Exclude:
    - lib/todo_lint/cli.rb
    - lib/todo_lint/options.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*.rb
