language: ruby
rvm:
  - 2.0.0
  - 2.2.4
  - 2.3.0
  - 2.4.0
before_install: gem install bundler -v 1.11
install: bundle install
script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec yardstick .
  - bundle exec fasterer
